# Product Manager Agent Contract (Simplified for testing)
agent: product-manager
version: "1.0"
autonomy_level: L3.5

allowed_actions:
  - read_evidence
  - read_roadmap
  - validate_task
  - modify_task_description

forbidden_actions:
  - write_code
  - override_governance

requires_approval:
  - roadmap_major_changes
  - blocking_p0_tasks

limits:
  max_iterations: 5
  max_retries: 2

invariants: {}
on_violation: halt
