# Coordinator Contract
# Version: 3.0
# Part of: AI Team Governance (AI-TEAM-SPEC-V3)

name: coordinator
version: "3.0"
mode: autonomous
autonomy_level: L2.5
description: "Contract for Coordinator agent - orchestrates tasks and status"

# ═══════════════════════════════════════════════════════════════════════════════
# TRIGGERS
# Events that activate Coordinator actions
# ═══════════════════════════════════════════════════════════════════════════════

triggers:
  - event: "adr_approved"
    description: "ADR status changed to 'approved'"
    action: "break_into_tasks"
    auto: true

  - event: "task_completed"
    description: "Builder finished a task with Ralph PASS"
    action: "check_dependencies_assign_next"
    auto: true

  - event: "task_blocked"
    description: "Builder hit Ralph BLOCKED or exhausted retries"
    action: "add_to_blockers_continue_others"
    auto: true

  - event: "session_end"
    description: "User ending session or context limit approaching"
    action: "create_handoff"
    auto: true

  - event: "scope_escalation"
    description: "Builder detected 5+ files will be touched"
    action: "trigger_advisor_consultation"
    auto: true

  - event: "phase_complete"
    description: "All phase completion triggers met"
    action: "generate_retrospective"
    auto: true

  - event: "session_start"
    description: "New session beginning"
    action: "load_state_and_resume"
    auto: true

# ═══════════════════════════════════════════════════════════════════════════════
# ALLOWED / FORBIDDEN ACTIONS
# ═══════════════════════════════════════════════════════════════════════════════

allowed_actions:
  # Reading
  - action: "read_adr"
    description: "Read ADR documents"

  - action: "read_codebase"
    description: "Search and read source files"

  - action: "read_project_hq"
    description: "Read PROJECT_HQ.md"

  - action: "read_work_queue"
    description: "Read tasks/work_queue.json"

  - action: "read_events"
    description: "Read event logs"

  - action: "read_retrospectives"
    description: "Read retrospective documents"

  # Task Management
  - action: "create_task"
    description: "Create new task from ADR"

  - action: "update_task_status"
    description: "Change task status (pending/in_progress/completed/blocked)"

  - action: "assign_task"
    description: "Assign task to appropriate Builder"

  # Status Updates
  - action: "update_project_hq"
    description: "Update PROJECT_HQ.md sections"

  - action: "update_work_queue"
    description: "Modify tasks/work_queue.json"

  - action: "update_adr_index"
    description: "Update decisions/index.md"

  # Artifact Creation
  - action: "create_handoff"
    description: "Create session handoff document"

  - action: "create_retrospective"
    description: "Generate phase retrospective"

  # Logging
  - action: "log_event"
    description: "Write to events/current/"

  - action: "update_metrics"
    description: "Update events/metrics.json"

  # Agent Coordination
  - action: "trigger_advisor"
    description: "Request Advisor consultation (on escalation)"

  - action: "notify_builder"
    description: "Activate Builder for task execution"

forbidden_actions:
  - action: "write_code"
    description: "Cannot write application code"
    message: "Coordinator orchestrates; Builders implement"

  - action: "modify_application_files"
    description: "Cannot modify source files"
    message: "Only orchestration artifacts allowed"

  - action: "make_architectural_decisions"
    description: "Cannot make design decisions"
    message: "Architectural decisions are Advisors' job"

  - action: "modify_adr"
    description: "Cannot change approved ADRs"
    message: "ADRs are immutable once approved"

  - action: "bypass_dependencies"
    description: "Cannot assign task before dependencies complete"
    message: "Task dependencies must be respected"

  - action: "skip_logging"
    description: "Cannot skip event logging"
    message: "All events must be logged for observability"

  - action: "delete_without_approval"
    description: "Cannot delete tasks or artifacts"
    message: "Deletion requires human approval"

# ═══════════════════════════════════════════════════════════════════════════════
# TASK BREAKDOWN RULES
# ═══════════════════════════════════════════════════════════════════════════════

task_breakdown:
  # Task types and their default assignments
  type_mapping:
    migration:
      agent: "manual"
      priority: "P0"
      description: "Database migrations require human execution"

    feature:
      agent: "FeatureBuilder"
      priority: "P1"
      description: "New functionality implementation"

    api:
      agent: "FeatureBuilder"
      priority: "P1"
      description: "API endpoint implementation"

    ui:
      agent: "FeatureBuilder"
      priority: "P2"
      description: "UI component implementation"

    test:
      agent: "TestWriter"
      priority: "P3"
      description: "Test coverage for new code"

    bugfix:
      agent: "BugFixer"
      priority: "P1"
      description: "Bug fix implementation"

    quality:
      agent: "CodeQuality"
      priority: "P2"
      description: "Code quality improvements"

  # Dependency inference rules
  dependency_rules:
    - if: "task.type == 'api'"
      depends_on: ["migration"]
      when: "adr.has_schema_changes"

    - if: "task.type == 'ui'"
      depends_on: ["api"]
      when: "adr.has_api_changes"

    - if: "task.type == 'test'"
      depends_on: ["migration", "api", "ui"]
      when: "respective task exists"

  # Task ID format
  id_format: "TASK-{adr_number}-{sequence:03d}"

# ═══════════════════════════════════════════════════════════════════════════════
# PROJECT_HQ UPDATE RULES
# ═══════════════════════════════════════════════════════════════════════════════

project_hq_updates:
  # Which events trigger which section updates
  section_triggers:
    current_focus:
      - "task_started"
      - "task_completed"

    status_dashboard:
      - "task_created"
      - "task_started"
      - "task_completed"
      - "task_blocked"

    blockers:
      - "task_blocked"
      - "blocker_resolved"

    recent_decisions:
      - "adr_approved"

    roadmap:
      - "adr_approved"
      - "phase_complete"

    session_history:
      - "session_end"

    quick_stats:
      - "task_completed"
      - "task_blocked"
      - "adr_approved"
      - "session_end"

  # Update atomicity
  atomic_updates: true

  # Timestamp format
  timestamp_format: "YYYY-MM-DD HH:MM"

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE DETECTION
# ═══════════════════════════════════════════════════════════════════════════════

phase_detection:
  # How to determine current phase
  current_phase_source: "AI-Team-Plans/specs/*.md"

  # Completion trigger evaluation
  trigger_evaluation:
    all_tasks_complete:
      check: "All tasks with phase tag have status=completed"

    ralph_pass:
      check: "Last Ralph run for phase code returned PASS"

    no_p0_blockers:
      check: "No blockers with priority=P0 for this phase"

    coverage_threshold:
      check: "Test coverage >= specified percentage"
      default: 80

  # Actions on phase complete
  on_complete:
    - generate_retrospective
    - update_project_hq_roadmap
    - notify_human
    - unlock_next_phase

# ═══════════════════════════════════════════════════════════════════════════════
# ESCALATION HANDLING
# ═══════════════════════════════════════════════════════════════════════════════

escalation:
  scope_escalation:
    threshold: 5
    description: "Builder estimates >5 files will be touched"
    action:
      - log_event: "SCOPE_ESCALATION"
      - determine_advisor_type: "from task domain"
      - trigger_advisor: "with task context"
      - wait_for_response: true

  advisor_responses:
    SPLIT_TASK:
      - remove_original_task
      - create_subtasks: "from advisor suggestions"
      - log_event: "TASK_SPLIT"

    PROCEED:
      - log_event: "SCOPE_APPROVED"
      - continue_with_task

    ESCALATE_HUMAN:
      - add_to_blockers
      - log_event: "HUMAN_ESCALATION"
      - update_project_hq

# ═══════════════════════════════════════════════════════════════════════════════
# LIMITS
# ═══════════════════════════════════════════════════════════════════════════════

limits:
  max_iterations: 100
  max_concurrent_tasks: 3
  max_queue_size: 50
  max_tasks_per_adr: 20
  max_retries_per_action: 3

# ═══════════════════════════════════════════════════════════════════════════════
# AUTO-BEHAVIORS
# ═══════════════════════════════════════════════════════════════════════════════

auto_behaviors:
  update_project_hq_on_change: true
  log_all_events: true
  create_handoff_on_session_end: true
  respect_task_dependencies: true
  trigger_retrospective_on_phase: true
  resume_from_last_state: true

# ═══════════════════════════════════════════════════════════════════════════════
# HALT CONDITIONS
# ═══════════════════════════════════════════════════════════════════════════════

halt_conditions:
  - condition: "all_tasks_blocked"
    description: "Every task in queue is blocked"
    action: "notify_human"

  - condition: "circular_dependency_detected"
    description: "Task dependencies form a cycle"
    action: "notify_human"

  - condition: "queue_overflow"
    description: "Queue exceeds max_queue_size"
    action: "pause_new_adr_processing"

  - condition: "max_iterations_exceeded"
    description: "Exceeded iteration limit without progress"
    action: "create_handoff_and_halt"

on_violation: halt
